language: cpp
compiler:
  - gcc
os:
  - linux
script:
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .. && make
  - cd $TRAVIS_BUILD_DIR/bin && ./UnitTests
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenal-dev libvorbis-dev libflac-dev
notifications:
  slack: cosyclub:mQ6pLLx0qmwmYUcvvk9TIT2O
  email:
    on_success: never
    on_failure: always
