language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
script:
  - mkdir build && cd build && cmake .. && make
  - cd bin && ./UnitTests
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenal-dev libvorbis-dev libflac-dev
notifications:
  slack: cosyclub:mQ6pLLx0qmwmYUcvvk9TIT2O
  email:
    on_success: never
    on_failure: always
