version: '{build}'
clone_folder: c:\ravecave
image: Visual Studio 2017
configuration: Debug
platform: x64

init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 Win64" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015 Win64" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 14 2013 Win64" )
  - echo %generator%

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G %generator%
build:
  project: c:\ravecave\build\ProjectTempo.sln
  verbosity: minimal
  parallel: true
